### ISSUE TITLE
question about  Introduction to Graduate Algorithms

### ISSUE THREAD

**Issue by YunjuanSUN** [m4ttsch/omscs-notes#65]
Dear author, thanks for your tremendous efforts in producing these materials which help me a lot. I am wondering that whether you will update the course named Introduction to Graduate Algorithms. It seems that it is a compulsory course. Thanks!

**Comment by m4ttsch** [comment]
I'll add those notes as soon as I can get into the course. Probably won't be for another few semesters :)
