### ISSUE TITLE
RAIT class only contains the first 4 lectures

### ISSUE THREAD

**Issue by owenzhudi** [m4ttsch/omscs-notes#72]
Hi, thanks for your contribution. I am taking RAIT class this semester and find that the lecture notes for RAIT class only contain the first 4 lectures till Kinematic Bicycle Model: 101. Are you planning to update the lecture notes for RAIT class? It would be a great help for the students taking this class.

**Comment by m4ttsch** [comment]
Sorry, I don't have time to do this at the moment.
